name: Update Team File

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

permissions:
  id-token: write
  contents: write
  checks: write
  pull-requests: write
  packages: write
  issues: write

jobs:
  post-action-link:
    name: Post Action Link
    runs-on: ubuntu-latest
    steps:
      - name: Post Action Link
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          COMMENT_BODY="This issue has been processed. You can view the action [here](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}). Please wait for 5-7 mins to get the action completed"
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -X POST \
            -d "{\"body\": \"$COMMENT_BODY\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/comments"

  update-teams-file:
    name: 'Setup TFY CLI DEV'
    if: contains(github.event.issue.labels.*.name, 'animal-jam') # Trigger only for issues with the specific label
    runs-on: ubuntu-latest
    steps:
      - name: Git Clone the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: 'pip'

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:rmescandon/yq
          sudo apt-get update && sudo apt-get install -y yq

      - name: Parse Issue
        id: issue-parser
        uses: ./.github/actions/process-team-request-form
        with:
          template-path: ./.github/ISSUE_TEMPLATE/teams_creation.yaml

      - name: Update Teams File
        id: update-teams
        if: steps.issue-parser.outcome == 'success'
        run: |
          echo "Updating teams file for team: $TEAM_NAME"
          FILE_PATH="test-folder/${TEAM_NAME}.yaml"
          if [ ! -f "$FILE_PATH" ]; then
            echo " Project file $TEAM_NAME does not exist. "
            exit 1
          fi
          yq eval ".members += [\"$EMAIL_ID\"] | .members |= unique" -i "$FILE_PATH"
          echo " Updated project file: $TEAM_NAME "
        env:
          TEAM_NAME: ${{ steps.issue-parser.outputs.project-name }}
          EMAIL_ID: ${{ steps.issue-parser.outputs.user-id }}

      - name: Create Pull Request
        id: create-pull-request
        if: steps.update-teams.outcome == 'success'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-team-file-${{ github.event.issue.number }}
          commit-message: "Update team file for ${{ github.event.issue.number }}"
          title: "Update team file for ${{ github.event.issue.number }}"
          body: "This PR updates the team file based on the issue form submission."
          labels: "automation"
          base: main

      - name: Post PR Link
        if: steps.create-pull-request.outcome == 'success'
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          PR_URL=${{ steps.create-pull-request.outputs.pull-request-url }}
          COMMENT_BODY="A pull request has been created to update the team file. You can view it [here]($PR_URL). Please ensure to get the PR reviewed and approved by the ihs-admin team before merging."
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -X POST \
            -d "{\"body\": \"$COMMENT_BODY\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/comments"