name: workflow-a1

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: write  # Required to use repository_dispatch

jobs:
  trigger-b1:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch to Repo B
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/boaluma/test-api-workflow/dispatches \
            -f "event_type=trigger-workflow-b1"
